version: '3.8'
services:
  stats-server:
    build: ./stats/stats-server
    container_name: ewm-stats-server
    ports:
      - "9090:9090"
    depends_on:
      - statsDB
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://statsDB:5432/statsDB
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password

  statsDB:
    image: postgres:14-alpine
    container_name: statsDB
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=statsDB
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password

  ewm-service:
    build: ./ewm
    container_name: ewm-main-service
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
      - ewmDB
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewmDB:5432/ewmDB
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
      - EWM-STATS-SERVICE_URI=http://stats-server:9090

  ewmDB:
    image: postgres:14-alpine
    container_name: ewmDB
    ports:
      - "6542:5433"
    environment:
      - POSTGRES_DB=ewmDB
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password