-- H2-compatible schema for EWM service

CREATE TABLE IF NOT EXISTS USERS
(
    ID    BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME  VARCHAR(50)  NOT NULL,
    EMAIL VARCHAR(320) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS CATEGORIES
(
    ID   BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS EVENTS
(
    ID                 BIGINT AUTO_INCREMENT PRIMARY KEY,
    ANNOTATION         VARCHAR(3000)    NOT NULL,
    CATEGORY_ID        BIGINT           NOT NULL,
    CREATED_ON         TIMESTAMP        NOT NULL,
    DESCRIPTION        VARCHAR(10000)   NOT NULL,
    EVENT_DATE         TIMESTAMP        NOT NULL,
    INITIATOR_ID       BIGINT           NOT NULL,
    LAT                DOUBLE           NOT NULL,
    LON                DOUBLE           NOT NULL,
    PAID               BOOLEAN          NOT NULL,
    PARTICIPANT_LIMIT  INTEGER          NOT NULL,
    PUBLISHED_ON       TIMESTAMP,
    REQUEST_MODERATION BOOLEAN,
    STATE              VARCHAR(100)     NOT NULL,
    TITLE              VARCHAR(200)     NOT NULL
);

CREATE TABLE IF NOT EXISTS REQUESTS
(
    ID           BIGINT AUTO_INCREMENT PRIMARY KEY,
    EVENT_ID     BIGINT      NOT NULL,
    CREATED      TIMESTAMP   NOT NULL,
    REQUESTER_ID BIGINT      NOT NULL,
    STATUS       VARCHAR(100) NOT NULL,
    CONSTRAINT UQ_REQUESTS UNIQUE (EVENT_ID, REQUESTER_ID)
);

CREATE TABLE IF NOT EXISTS COMPILATIONS
(
    ID     BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITLE  VARCHAR(128) NOT NULL,
    PINNED BOOLEAN      NOT NULL
);

CREATE TABLE IF NOT EXISTS COMPILATION_EVENT
(
    COMPILATION_ID BIGINT NOT NULL,
    EVENT_ID       BIGINT NOT NULL,
    CONSTRAINT COMPILATION_EVENT_PK PRIMARY KEY (COMPILATION_ID, EVENT_ID)
);

CREATE TABLE IF NOT EXISTS COMMENTS
(
    ID           BIGINT AUTO_INCREMENT PRIMARY KEY,
    TEXT_COMMENT VARCHAR(5000)   NOT NULL,
    AUTHOR_ID    BIGINT          NOT NULL,
    EVENT_ID     BIGINT          NOT NULL,
    CREATED_ON   TIMESTAMP       NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_comments_event_id ON COMMENTS (EVENT_ID);
CREATE INDEX IF NOT EXISTS ix_comments_author_id ON COMMENTS (AUTHOR_ID);
